### ISSUE TITLE
Run in parallel?

### ISSUE THREAD

**Issue by statslover123** [brandon-mosqueda/SKM#1]
Is there a way to run models in parallel ? (gbm, rf) 

Especially for grid search or bayesian optimization of hyperparameters, large data can be very slow to test without running in parallel.

**Comment by brandon-mosqueda** [comment]
Currently is not supported yet, it would be great as you mentioned for hyperparameter tuning but at least both libraries SKM uses internally for gbm and rf use parallelization to build the trees, so in theory there is no much to do with respect of these two algorithms.
