### ISSUE TITLE
Negatitive coef() from random forest model

### ISSUE THREAD

**Issue by statslover123** [brandon-mosqueda/SKM#3]
What is interpreation of negative coef values for a predictor in random forest model?

**Comment by brandon-mosqueda** [comment]
I wasn't completely sure but I find this [site](https://blog.hwr-berlin.de/codeandstats/variable-importance-in-random-forests/) and they mentioned this:

> The default method to compute variable importance is the mean decrease in impurity (or gini importance) mechanism: At each split in each tree, the improvement in the split-criterion is the importance measure attributed to the splitting variable, and is accumulated over all the trees in the forest separately for each variable. 

so a negative value can be interpreted not as the decrease in impurity but the increase. If you need more information you can check the documentation of the function it is used to obtained these values ([https://www.rdocumentation.org/packages/randomForestSRC/versions/3.2.0/topics/vimp.rfsrc](https://www.rdocumentation.org/packages/randomForestSRC/versions/3.2.0/topics/vimp.rfsrc)), there is a reference paper there.

**Comment by statslover123** [comment]
thank you! SKM is great for many situations of  n<<p,not just genetic, thank you for the help
