### ISSUE TITLE
Deep Learning Error

### ISSUE THREAD

**Issue by statslover123** [brandon-mosqueda/SKM#4]
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  RuntimeError: Detected a call to `Model.fit` inside a `tf.function`. `Model.fit is a high-level endpoint that manages its own `tf.function`. Please move the call to `Model.fit` outside of all enclosing `tf.function`s. Note that you can call a `Model` directly on `Tensor`s inside a `tf.function` like: `model(x)`.
  
  I get the above error with several attempts to run deep learning, univariate or multivariate, models.

model <- SKM::deep_learning(
    x=as.matrix(kerntest[training,1:32]), y=as.matrix(use3[training,71:82]),
    epochs_number = c(1,5,10),
    learning_rate = c(0.01,0.005),
    tune_type = "grid_search",
    tune_cv_type = "k_fold",
    tune_folds_number = 5
  )

**Comment by brandon-mosqueda** [comment]
I suspect you find this error because your version of the tensorflow and/or keras libraries. Try updating them with the following commands:

```r
devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
```

**Comment by statslover123** [comment]
I think the issue with how I have paths configured, I was able to fix it

**Comment by brandon-mosqueda** [comment]
Yes, sometimes that's a headache.
