### ISSUE TITLE
PLS methods all give same results?

### ISSUE THREAD

**Issue by statslover123** [brandon-mosqueda/SKM#5]
Kernel,orthogonal, wide kernel etc all give the same prediction accuracy (same test train split, same number of latent variables to predict with)

Is this expected?

**Comment by brandon-mosqueda** [comment]
Yes, it is possible. What it would be strange is that you get the exact same predictions using one kernel or another. But if you have this case, try providing some code example, with toy data for reproducing your problem.

**Comment by statslover123** [comment]
I get the same predictions, however, using the base pls() package the plsr() function, I get the same results as using SKM as the interface. So I think that there is no issue
