### ISSUE TITLE
Kernelize gives same results?

### ISSUE THREAD

**Issue by statslover123** [brandon-mosqueda/SKM#6]
Using the iris dataset, I am getting the same matrix with linear and arc cosine, and sigmoid kernel function.

**Comment by brandon-mosqueda** [comment]
Thank you for pointing out that. We have discovered that kernelize function has not passed correctly the kernel parameter to another internal function and that was provoking always to compute the linear kernel.

I have fixed that issue and commited the update. If you reinstall the library wit `devtools::install_github("brandon-mosqueda/SKM")` you will see the change.

The following code now gives the expected results:

```r
rm(list = ls())

library(SKM)

linear <- kernelize(iris, kernel = "linear")
sigmoid <- kernelize(iris, kernel = "sigmoid")
arc_cosine <- kernelize(iris, kernel = "arc_cosine")

all(linear == sigmoid)      # FALSE
all(linear == arc_cosine)   # FALSE
all(sigmoid == arc_cosine)  # FALSE

# They are different
cbind(linear[, 2], sigmoid[, 2], arc_cosine[, 2])
```

**Comment by statslover123** [comment]
that fixed it, thank you!
